INSERT INTO key_english (b, n) VALUES (1, 'Genesis');
INSERT INTO key_english (b, n) VALUES (2, 'Exodus');
INSERT INTO key_english (b, n) VALUES (3, 'Leviticus');
INSERT INTO key_english (b, n) VALUES (4, 'Numbers');
INSERT INTO key_english (b, n) VALUES (5, 'Deuteronomy');
INSERT INTO key_english (b, n) VALUES (6, 'Joshua');
INSERT INTO key_english (b, n) VALUES (7, 'Judges');
INSERT INTO key_english (b, n) VALUES (8, 'Ruth');
INSERT INTO key_english (b, n) VALUES (9, '1 Samuel');
INSERT INTO key_english (b, n) VALUES (10, '2 Samuel');
INSERT INTO key_english (b, n) VALUES (11, '1 Kings');
INSERT INTO key_english (b, n) VALUES (12, '2 Kings');
INSERT INTO key_english (b, n) VALUES (13, '1 Chronicles');
INSERT INTO key_english (b, n) VALUES (14, '2 Chronicles');
INSERT INTO key_english (b, n) VALUES (15, 'Ezra');
INSERT INTO key_english (b, n) VALUES (16, 'Nehemiah');
INSERT INTO key_english (b, n) VALUES (17, 'Esther');
INSERT INTO key_english (b, n) VALUES (18, 'Job');
INSERT INTO key_english (b, n) VALUES (19, 'Psalms');
INSERT INTO key_english (b, n) VALUES (20, 'Proverbs');
INSERT INTO key_english (b, n) VALUES (21, 'Ecclesiastes');
INSERT INTO key_english (b, n) VALUES (22, 'Song of Solomon');
INSERT INTO key_english (b, n) VALUES (23, 'Isaiah');
INSERT INTO key_english (b, n) VALUES (24, 'Jeremiah');
INSERT INTO key_english (b, n) VALUES (25, 'Lamentations');
INSERT INTO key_english (b, n) VALUES (26, 'Ezekiel');
INSERT INTO key_english (b, n) VALUES (27, 'Daniel');
INSERT INTO key_english (b, n) VALUES (28, 'Hosea');
INSERT INTO key_english (b, n) VALUES (29, 'Joel');
INSERT INTO key_english (b, n) VALUES (30, 'Amos');
INSERT INTO key_english (b, n) VALUES (31, 'Obadiah');
INSERT INTO key_english (b, n) VALUES (32, 'Jonah');
INSERT INTO key_english (b, n) VALUES (33, 'Micah');
INSERT INTO key_english (b, n) VALUES (34, 'Nahum');
INSERT INTO key_english (b, n) VALUES (35, 'Habakkuk');
INSERT INTO key_english (b, n) VALUES (36, 'Zephaniah');
INSERT INTO key_english (b, n) VALUES (37, 'Haggai');
INSERT INTO key_english (b, n) VALUES (38, 'Zechariah');
INSERT INTO key_english (b, n) VALUES (39, 'Malachi');
INSERT INTO key_english (b, n) VALUES (40, 'Matthew');
INSERT INTO key_english (b, n) VALUES (41, 'Mark');
INSERT INTO key_english (b, n) VALUES (42, 'Luke');
INSERT INTO key_english (b, n) VALUES (43, 'John');
INSERT INTO key_english (b, n) VALUES (44, 'Acts');
INSERT INTO key_english (b, n) VALUES (45, 'Romans');
INSERT INTO key_english (b, n) VALUES (46, '1 Corinthians');
INSERT INTO key_english (b, n) VALUES (47, '2 Corinthians');
INSERT INTO key_english (b, n) VALUES (48, 'Galatians');
INSERT INTO key_english (b, n) VALUES (49, 'Ephesians');
INSERT INTO key_english (b, n) VALUES (50, 'Philippians');
INSERT INTO key_english (b, n) VALUES (51, 'Colossians');
INSERT INTO key_english (b, n) VALUES (52, '1 Thessalonians');
INSERT INTO key_english (b, n) VALUES (53, '2 Thessalonians');
INSERT INTO key_english (b, n) VALUES (54, '1 Timothy');
INSERT INTO key_english (b, n) VALUES (55, '2 Timothy');
INSERT INTO key_english (b, n) VALUES (56, 'Titus');
INSERT INTO key_english (b, n) VALUES (57, 'Philemon');
INSERT INTO key_english (b, n) VALUES (58, 'Hebrews');
INSERT INTO key_english (b, n) VALUES (59, 'James');
INSERT INTO key_english (b, n) VALUES (60, '1 Peter');
INSERT INTO key_english (b, n) VALUES (61, '2 Peter');
INSERT INTO key_english (b, n) VALUES (62, '1 John');
INSERT INTO key_english (b, n) VALUES (63, '2 John');
INSERT INTO key_english (b, n) VALUES (64, '3 John');
INSERT INTO key_english (b, n) VALUES (65, 'Jude');
INSERT INTO key_english (b, n) VALUES (66, 'Revelation');